---
title: "ABM test"
author: "Marie"
date: "5/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Packages
```{r}
pacman::p_load(tidyverse,
               network,
               igraph,
               ggraph,
               #tidygraph,
               intergraph,
              # patchwork,
              # statnet,
               #magrittr,
               ggnetwork,
               #EpiModel,
               #netdiffuseR
               )
```


Generate network
```{r}
generate_moore <- function(n, p, nei){
 moore <-  make_lattice(c(sqrt(n),sqrt(n)), nei = nei) %>% 
   rewire(each_edge(p = p)) %>% 
   asNetwork(.) 
 return(moore)
}
mtest <- generate_moore(n = 100, p = 0, nei = 2)
plot(mtest)
get.neighborhood(mtest)

mtest <- make_lattice(c(10,10), nei = 2)
degrees <- degree(mtest)
mean(degrees)



moore <- make_lattice(c(600, 400), nei =2) %>% rewire(each_edge(p = 10^-2)) 
moore <- moore %>% asNetwork(.) 
moore_adj <- moore[, ]

sqrt(40000)

generate_scalefree <- function(n, degrees, gamma, p = 0){
  degs <- sample(1:degrees, n, replace=TRUE, prob=(1:degrees)^-gamma)
  if (sum(degs) %% 2 != 0) { degs[1] <- degs[1] + 1 } ### Note, that we correct the degree sequence if its sum is odd
  degs <- degs * 2
  scale_free <- sample_degseq(degs, method = "vl") 
  scale_free <- scale_free %>% rewire(each_edge(p = p)) #ska være meget lav
  scale_free <- scale_free %>% asNetwork(.)
  return(scale_free)
} 

generate_scalefree(20000, 150, 2.3, p=10^-4)
```

Setting initial adopters
```{r}
moore <- generate_moore(100, 0.01, 2)
max.time <- 8
tau <- 2/6
n <- 100

  
adopters <- rep(F, n)
# Choose a person at random
initial_adopter <- base::sample(seq_len(n), size = 1) #takes one node from the sequence of nodes and classifies it as the inital 

#adopter
initial_neighbors <- get.neighborhood(moore, initial_adopter) #shows the 3 neighbors that the infected adopter has
adopters[c(initial_adopter, initial_neighbors)] <- T #setting all neighbors to the initial infected node as infected

#moore adj
adj <- moore[, ]
diag(adj) <- 0 
#perc activated
(nei_activated_perc <- adj / rowSums(adj))

adopt <- vector(mode = "list", length = max.time) 
adopt[[1]] <- adopters
df_1 <- data.frame(
  round = 1,
  tau = tau_vec,
  adopters = adopters,
  id = 1:n
)

for (t in 2:rounds) {
adopt[[t]] <- ifelse(adopters, TRUE, ((nei_activated_perc %*% adopt[[t - 1]]) >= tau_vec)) 
 
df <- data.frame(
    round = t,
    tau = tau_vec,
    adopters = adopt[[t]],
    id = 1:n
    )
if (t == 2) {
  adopt_dat <- df
}else{
 adopt_dat <- rbind(adopt_dat, df)
}
}

adopt_dat <- rbind(df_1, adopt_dat)

```
```{r}
contagion_sim <- function(condition = "base_tau", high_status = F, rep, net_type = "moore", rounds, tau = 0, n, nei, p = 0, n_high, degrees = 0, gamma = 0, stochastic = F){ #assumption network
  ##HVOR SKA if(high_status == T) VÆRE??
  for (i in 1:rep){
#generate network
    if(net_type == "moore"){
      network <- generate_moore(n, p, nei)
    }
    if(net_type == "scale_free"){
      network <- generate_scalefree(n, degrees, gamma, p)
      print(i)
    }
#preparing first adopter list 
adopters <- rep(F, n)
# Choose a person at random
initial_adopter <- base::sample(seq_len(n), size = 1) #takes one node from the sequence of nodes and classifies it as the inital 
#adopter
initial_neighbors <- get.neighborhood(network, initial_adopter) #shows the 3 neighbors that the infected adopter has
adopters[c(initial_adopter, initial_neighbors)] <- T #setting all neighbors to the initial infected node as infected
print(condition)
print(i)

#preparing the matrix
adj <- network[, ]
diag(adj) <- 0 
(nei_activated_perc <- adj / rowSums(adj))

if (high_status == T){
  #Update adjacency matrix and then move on
}

adopt <- vector(mode = "list", length = rounds) 
adopt[[1]] <- adopters

if(condition == "base_tau" & stochastic == F){
#preparing tau list
tau_vec <- as.vector(rep(tau, nrow(adj)))
for (t in 2:rounds) {
adopt[[t]] <- ifelse(adopters, TRUE, ((nei_activated_perc %*% adopt[[t - 1]]) >= tau_vec)) 
 
df <- data.frame(
    round = t,
    tau = tau_vec,
    adopters = adopt[[t]],
    id = 1:nrow(adj),
    network = i
    )

if (t == 2) {
  adopt_dat <- df
}else{
 adopt_dat <- rbind(adopt_dat, df)
}
}
  df_1 <- data.frame(
  round = 1,
  tau = tau_vec,
  adopters = adopters,
  id = 1:nrow(adj),
  network = i
  )
  adopt_dat <- rbind(df_1, adopt_dat)
  if (i == 1){
    all_adopters <- adopt_dat
  }else{
    all_adopters <- rbind(all_adopters, adopt_dat)
  }
}

if(condition == "random_tau" & stochastic == F){ 
   tau_norm <- rnorm(nrow(adj),tau, tau/3)
   tau_vec_random <- as.vector(sample(tau_norm))
   for (t in 2:rounds) {
adopt[[t]] <- ifelse(adopters, TRUE, ((nei_activated_perc %*% adopt[[t - 1]]) >= tau_vec_random)) 
 
df <- data.frame(
    round = t,
    tau = tau_vec_random,
    adopters = adopt[[t]],
    id = 1:nrow(adj),
    network = i
    )
if (t == 2) {
  adopt_dat <- df
  }else{
    adopt_dat <- rbind(adopt_dat, df)
  }
}
   df_1 <- data.frame(
  round = 1,
  tau = tau_vec_random,
  adopters = adopters,
  id = 1:nrow(adj),
  network = i
  )
  adopt_dat <- rbind(df_1, adopt_dat)
  if (i == 1){
    all_adopters <- adopt_dat
  }else{
    all_adopters <- rbind(all_adopters, adopt_dat)
  }
  }

if(stochastic == T){
  if (condition == "base_tau"){
    tau_vec = as.vector(rep(tau, nrow(adj)))
  }
  else if (condition == "random_tau"){
    tau_vec = rnorm(nrow(adj),tau, tau/3) #Some taus are negative which is not good! 
    #They should only be pos so therefore sd = tau/3
  }
   for (t in 2:rounds){
    list <- adopt[[t-1]]
    m = nei_activated_perc %*% adopt[[t-1]] # m = p = percentage activated neighbors
    q = m - tau_vec + 0.5
    for (s in 1:length(list)){
    L = 1/(1+exp((.5-q[s])*10)) #We just use M = 10 because that is was Macy does but this could be discussed
    activation = rbinom(1,1,prob = L)
    if (activation == 1) {
      list[s] = TRUE}
    else if (activation == 0) {  #If we remove this else if statement, maybe they cant turn of?
      list[s] = FALSE}
    }
    adopt[[t]] <- list
  }
}

if(condition == "high_node"){
    #making highnodes/influencers 
high_node_vec <- rep(F, n)
influencer <- base::sample(seq_len(n), size = n_high)
high_node_vec[c(influencer)] <- T
adopters[c(influencer)] <- T
#sw net - med high-node!
adopt <- vector(mode = "list", length = rounds)
adopt[[1]] <- adopters
    for (t in 2:rounds) {
      
      adopt[[t]] <- ifelse(adopters, TRUE, ((adj_nei %*% adopt[[t - 1]]) >= tau)) 
      active_high <- adopt[[t-1]] & high_node_vec
      adopt[[t]] <- ifelse(adopters, TRUE, ((adj %*% active_high) == 1))
      
      df <- data.frame(
        round = t,
        tau = rep(tau, nrow(adj)),
        active_high = active_high,
        high_node = high_node_vec,
        adopters = adopt[[t]],
        id = 1:nrow(adj),
        network = i
        )
    if(t == 2){
        adopt_dat <- df
        }else{
          adopt_dat <- rbind(adopt_dat, df)
        }
      }
    
  df_1 <- data.frame(
  round = 1,
  tau = rep(tau, nrow(adj)),
  active_high = active_high,
  high_node = high_node_vec,
  adopters = adopters,
  id = 1:nrow(adj),
  network = i
  )
    
  adopt_dat <- rbind(df_1, adopt_dat)
  
  if (i == 1){
    all_adopters <- adopt_dat
  }else{
    all_adopters <- rbind(all_adopters, adopt_dat)
  }
  }
  }
  return(all_adopters)
}
#rep, rounds, tau = 0, net_type = "moore", nodes, nei, p = 0, degrees = 0, gamma = 0
moore_all <- contagion_sim(rep = 5, rounds = 10, tau = .33, n = 100, nei = 2, p = 10^-2)
scale_free_all <- contagion_sim(rep = 5, rounds = 10, tau = .33, net_type = "scale_free", n = 10000, degrees = 100, gamma = 2.3)
moore_highnode <- contagion_sim(condition = "high_node", rep = 5, rounds = 10, tau = .33, net_type = "moore", nei = 2, n = 100, p = .01, n_high = 1)

scale_free_all$adopters <- as.numeric(scale_free_all$adopters)
#watching the overall propagation for network one
scale_free_all %>% filter(network==1) %>% 
  group_by(round) %>% 
  summarise(sum_adopt = sum(adopters)) %>%
  ggplot(aes(x = round, y = sum_adopt)) + 
  geom_line()
```

Plots
```{r}
data.frame(
  t = 1:rounds,
  n.adopt = sapply(adopt, sum)
) %>%
  ggplot(aes(x = t, y = n.adopt)) + 
  geom_line()



# Let's plot a few frames
set.seed(330)
sf_layout <- ggnetwork(sf) %>% 
  rename(id = vertex.names)

```
high node
```{r}
moo <- generate_moore(100, 0.01, 2)

n = 100
adopters <- rep(F, n) #repeat "FALSE" 50 times - initially none are infected
initial.adopter <- base::sample(seq_len(n), size = 1) #takes one node from the sequence of nodes and classifies it as the inital adopter
initial.neighbors <- get.neighborhood(moo, initial.adopter) #shows the 3 neighbors that the infected adopter has
adopters[c(initial.adopter, initial.neighbors)] <- T #setting all neighbors to the initial infected node as infected

#making highnodes/influencers 
high_node_vec <- rep(F, n)
influencer <- base::sample(seq_len(n), size = 1)
high_node_vec[c(influencer)] <- T
high_node_neighbors <- get.neighborhood(moo, influencer)

adj <- moo[, ] ## making our small world network an adjacency matrix
diag(adj) <- 0  # set the diagonal to 0, b/c people don't weight themselves
# We could take the sum...
(adj_nei <- adj / rowSums(adj))

#gives the neighbors of the highnode
# adopters %*% high_node
adopters[c(influencer)] <- T
adopters & high_node_vec #highnode 10 is an adopter as well
active_high <- adopters & high_node_vec

ifelse(adopters, TRUE, ((adj %*% active_high) == 1))
(adj_perc <- adj / rowSums(adj))
adj[c(active_high)]

#sw net - med high-node!
adopt <- vector(mode = "list", length = max.time)
adopt[[1]] <- adopters
max.time = 10
for (t in 2:max.time) {
  print(t)
  adopt[[t]] <- ifelse(adopters, TRUE, ((adj_nei %*% adopt[[t - 1]]) >= tau)) #for the second element in the list "adopt" we test whether the fraction of adopters in the round before is greater than tau. we know that it will succeed the first round because we have determined the adopters to be infected. # we calculate the people who are above our threshold
  active_high <- adopt[[t-1]] & high_node_vec
  adopt[[t]] <- ifelse(adopters, TRUE, ((adj %*% active_high) == 1))
}



```


Logistic funciton
```{r}
p_load(tidyverse, ggnetwork, intergraph, igraph)

#Set up network
sw.net <- igraph::watts.strogatz.game(1, 50, 2, p = 0.005) %>%
  intergraph::asNetwork(.) 

n = 50
# Set up vector to indicate adoption
adopters <- rep(F, 50)

# Choose a person at random
initial.adopter <- sample(seq_len(n), size = 1)

# Get the list of people they're attached to
initial.neighbors <- get.neighborhood(sw.net, initial.adopter)

# Set them all as "adopters"
adopters[c(initial.adopter, initial.neighbors)] <- T

#Make adjacency matrix
adj.mat <- sw.net[, ]
diag(adj.mat) <- 0

#Calculate percentage
adj.mat.rn <- adj.mat / rowSums(adj.mat)

max.time = 8
adopt <- vector(mode = "list", length = max.time)
adopt[[1]] <- adopters
adopt

stochastic <- T
tau_vec <- rep(0.1,50)
M <- 10

for (t in 2:max.time){
  p <- adj.mat.rn %*% adopt[[t-1]]
  list <- adopt[[t-1]]
  for (i in 1:length(list)){
    if (stochastic == T & p[i]>=tau_vec[i]){
    L = 1/(1+exp((.5-p[i])*M))
    activation = rbinom(1,1,prob = L)
      if (activation == 1) {
        list[i] = TRUE}
        else if (activation == 0) {
        list[i] = FALSE}
    }
      else {
        list[i] = FALSE
      }
    
    adopt[[t]] <- list
    
    if (stochastic == F){
      adopt[[t]] <- ifelse(adopters, TRUE, ((adj.mat.rn %*% adopt[[t - 1]]) >= tau_vec))
    }
  }
}

```

Stochastic
```{r}
library(ggplot2)
M = 8
wow = seq(0, 1, by = 0.01)

sto <- tibble(p = wow, L = 1/(1+exp((.5-p)*M)))


ggplot(sto, aes(p,L))+
  geom_point()+
  geom_line()
#for an agents with tau = 4/10, L when p is 0.4 is equal to L for 0.5
#Which means that the L we want for 4/10 activated neighbors is equal to p-tau  + 0.5

tau = 0.6
p = 0.4

q = p-tau + 0.5
1/(1+exp((.5-q)*M))
```

